### PR TITLE
attempts to fix issue #249

### LINKED ISSUE #249: when a league day ends exactly on an hour, instead of continuing immediately, it says it will start in 1440 minutes instead.
Discord_2021-05-09_07-49-22
Discord_2021-05-09_07-49-05
Discord_2021-05-09_07-48-52
Discord_2021-05-09_07-49-33

### PR DESCRIPTION
**Pull request by chesse20**
this is an attempt to fix #249 i don't know if it'll work or not but an attempt was made

### CODE REVIEW

**Comment by Sakimori** [comment]
this is the right idea! When I get a chance I'll tidy up the actual values and then merge

**Comment by chesse20** [comment]
i don't want to sound like im rushing you, but this issue just popped again for the fourth time in 100 games and our leagues been delayed by a total of 96 hours now in one season

**Comment by Sakimori** [comment]
hi! this is rude! i'm on a trip away from home right now and can't deal with this at the moment!

**Comment by chesse20** [comment]
oh sorry i didn't know i tried to not sound rude im not very good at that sometimes sorry sorry

**Pull request closed without merging**
