### PR TITLE
Draft Feature

### LINKED ISSUE #47: draft mode for building a team
low priority. onomancer-generated names put into a pool, some number of users build teams from said pool

### PR DESCRIPTION
**Pull request by jmaliksi**
Resolves #47 

This implements the Draft. See #47 for design notes.

### CODE REVIEW

**Comment by Sakimori** [comment]
looks good so far! all caps variables make it really obvious that this isn't mine though :3

**Comment by jmaliksi** [comment]
do you want me to conform to your standard or is it fine as is

also should we merge this into master without the discord bot stuff since it's not hooked up to anything, or do you want it all to go in at once

**Comment by Sakimori** [comment]
it's fine as is, i think. we should probably have a branch for the drafting feature though?

**Comment by Sakimori** [comment]
can you move this to the indev branch so i can sort out the conflicts and test with a live-alike database?

**Pull request merged**
